/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface JoKenPoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getBalance"
      | "getBid"
      | "getStatus"
      | "getcomission"
      | "play1"
      | "play2"
      | "player1"
      | "player2"
      | "setBid"
      | "setcomission"
      | "win"
      | "winCount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getBid", values?: undefined): string;
  encodeFunctionData(functionFragment: "getStatus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getcomission",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "play1", values: [string]): string;
  encodeFunctionData(functionFragment: "play2", values: [string]): string;
  encodeFunctionData(functionFragment: "player1", values?: undefined): string;
  encodeFunctionData(functionFragment: "player2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setcomission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "win", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "winCount",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getcomission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "play1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "play2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "player1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "player2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setcomission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "win", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "winCount", data: BytesLike): Result;
}

export interface JoKenPo extends BaseContract {
  connect(runner?: ContractRunner | null): JoKenPo;
  waitForDeployment(): Promise<this>;

  interface: JoKenPoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getBid: TypedContractMethod<[], [bigint], "view">;

  getStatus: TypedContractMethod<[], [string], "view">;

  getcomission: TypedContractMethod<[], [bigint], "view">;

  play1: TypedContractMethod<[Choice_string: string], [void], "payable">;

  play2: TypedContractMethod<[Choice_string2: string], [void], "payable">;

  player1: TypedContractMethod<[], [string], "view">;

  player2: TypedContractMethod<[], [string], "view">;

  setBid: TypedContractMethod<[newBid: BigNumberish], [void], "nonpayable">;

  setcomission: TypedContractMethod<
    [newComissionPercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  win: TypedContractMethod<[], [string], "nonpayable">;

  winCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getcomission"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "play1"
  ): TypedContractMethod<[Choice_string: string], [void], "payable">;
  getFunction(
    nameOrSignature: "play2"
  ): TypedContractMethod<[Choice_string2: string], [void], "payable">;
  getFunction(
    nameOrSignature: "player1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "player2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBid"
  ): TypedContractMethod<[newBid: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setcomission"
  ): TypedContractMethod<
    [newComissionPercent: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "win"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "winCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  filters: {};
}
